variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VERSION_LAST_INCREASE: 0
  VERSION_MAJOR: 4
  VERSION_MINOR: 0

before_script:
  - git remote set-url origin https://${CI_USER}:${CI_PUSH_TOKEN}@gitlab.kharkov.dbbest.com/android/nettest.git
  - git config --global user.email '${CI_USER_EMAIL}'
  - git config --global user.name '${CI_USER_NAME}'
  - git submodule update --init --recursive
  - echo $JAVA_HOME
  - echo $ANDROID_HOME
  - echo $PATH
  - chmod +x ./gradlew
  - export VERSION_PATCH=$((BUILD_NUMBER-VERSION_LAST_INCREASE))
  - export VERSION_CODE=$(( (((VERSION_MAJOR*1000000)+(VERSION_MINOR*10000)+VERSION_PATCH))*10))
  - export VERSION_NAME="$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH"
  - export RELEASE_NOTES="Created from commit $CI_PROJECT_URL/commit/$CI_COMMIT_SHA"
  - export BUILD_TIME=$(date +%s%3N)
  - echo "${VERSION_PATCH}"
  - echo "${VERSION_CODE}"
  - echo "${VERSION_NAME}"
  - echo "${RELEASE_NOTES}"
  - echo "${BUILD_TIME}"

stages:
  - init
  - check
  - distribution
  - gitTag

init:
  stage: init
  script:
    - echo "${BUILD_NUMBER}"
    - NEW_NUMBER=$((++BUILD_NUMBER))
    - echo "next build number $NEW_NUMBER"
    - 'curl --request PUT --header "PRIVATE-TOKEN: ${CI_PUSH_TOKEN}" "https://gitlab.kharkov.dbbest.com/api/v4/projects/${CI_PROJECT_ID}/variables/BUILD_NUMBER" --form "value=${NEW_NUMBER}"'
  only:
    - develop

appLint:
  stage: check
  script:
    - ./gradlew :app:ktlint
    - ./gradlew :app:lintLocalDevDebug
  only:
    refs:
      - /fix\/.*/
      - /feature\/.*/
      - /hotfix\/.*/
      - /test\/.*/

coreLint:
  stage: check
  script:
    - ./gradlew :core:ktlint
    - ./gradlew :core:lint
  only:
    refs:
      - /fix\/.*/
      - /feature\/.*/
      - /hotfix\/.*/
      - /test\/.*/

controlClientLint:
  stage: check
  script:
    - ./gradlew :control_client:ktlint
    - ./gradlew :control_client:lint
  only:
    refs:
      - /fix\/.*/
      - /feature\/.*/
      - /hotfix\/.*/
      - /test\/.*/

checkRTRBuild:
  stage: check
  script:
    - rm -rf private
    - ./gradlew clean
    - ./gradlew assembleRtrDebug
  only:
    refs:
      - /fix\/.*/
      - /feature\/.*/
      - /hotfix\/.*/
      - /test\/.*/

uiTests:
  stage: check
  variables:
    TEST_AVD_NAME: Pixel_2_API_26
  script:
    - export DISPLAY=:0
    - chmod a+x ./run-ui-tests.sh
    - ./run-ui-tests.sh $TEST_AVD_NAME
  tags:
    - RTR_UI_TESTS
  only:
    refs:
      - develop
    variables:
      - $UI_TEST_RUN

distributeLocalApp:
  stage: distribution
  script:
    - ./gradlew assembleLocalStageDebug -PbuildVersionCode=${VERSION_CODE} -PbuildVersionName=${VERSION_NAME} -PreleaseNotes="${RELEASE_NOTES}"
    - ./gradlew crashlyticsUploadDistributionLocalStageDebug
    - ./gradlew assembleLocalDemoRelease -PbuildVersionCode=${VERSION_CODE} -PbuildVersionName=${VERSION_NAME} -PreleaseNotes="${RELEASE_NOTES}"
    - ./gradlew crashlyticsUploadDistributionLocalDemoRelease
  only:
    - develop
  artifacts:
    name: "local-$VERSION_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - app/build/outputs

generateDocumentation:
  stage: distribution
  script:
    - ./gradlew dokka dokkaMarkdown
  only:
    - develop
  artifacts:
    name: "docs-$VERSION_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - build_results/javadoc
      - build_results/markdown

gitTag:
  stage: gitTag
  script:
    - git tag "${VERSION_NAME}"
    - git push origin --tags
  only:
    - develop